name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker Help
        run: docker --help

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Gem Check
        run: gem --help

      - name: Test Consumer
        run: go clean -testcache && go test -tags=consumer ./app/...
