name: Build

on:
  push:
    branches: [development, master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eneskzlcn/pact-with-go:go-1.18
      ports:
        - 80
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Build
        run: go build -v ./...

      - name: Test Consumer
        run: go clean -testcache && go test -tags=consumer ./app/...